services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ant-backend-dev
    ports:
      - "8000:8000"
    environment:
      - CHROME_HEADLESS=True
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - ant-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    container_name: ant-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ant-network

networks:
  ant-network:
    driver: bridge
